#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#ifndef WEBSERVER_CONF_CFS_CONNS
#define WEBSERVER_CONF_CFS_CONNS 2
#endif

#ifndef BORDER_ROUTER_CONF_WEBSERVER
#define BORDER_ROUTER_CONF_WEBSERVER 1
#endif

#if BORDER_ROUTER_CONF_WEBSERVER
#define UIP_CONF_TCP 1
#endif

//PACKET CONFIGURATION
#define UDP_SOURCE_1 0
#define UDP_SOURCE_2 1
#define UDP_PORT_1 3001
#define UDP_PORT_2 3002


//LOGGING
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_FRAMER LOG_LEVEL_WARN
#define TSCH_LOG_CONF_PER_SLOT 0

//CHANNEL CONFIGURATION
#undef IEEE802154_CONF_DEFAULT_CHANNEL
#define IEEE802154_CONF_DEFAULT_CHANNEL 16
#undef IEEE802154_CONF_PANID
#define IEEE802154_CONF_PANID 0xABD2

//SECURITY
//#define LLSEC802154_CONF_ENABLED 1
//#define CSMA_CONF_LLSEC_SECURITY_LEVEL 5
//#define CSMA_CONF_LLSEC_KEY_ID_MODE 2

#endif /* PROJECT_CONF_H_ */
